In [1]:
import pandas as pd

In [2]:
market_data = pd.read_csv("data/market_data.csv")
market_data.head()

,Price,Close,Close.1,Close.2,High,High.1,High.2,Low,Low.1,Low.2,Open,Open.1,Open.2,Volume,Volume.1,Volume.2
0,Ticker,AAPL,SPY,TSLA,AAPL,SPY,TSLA,AAPL,SPY,TSLA,AAPL,SPY,TSLA,AAPL,SPY,TSLA
1,Date,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2024-01-02,183.56219482421875,459.9911804199219,248.4199981689453,186.33085840634024,460.9838811377681,251.25,181.83178197139316,457.8890273530107,244.41000366210938,185.05528848269014,459.51431341639926,250.0800018310547,82488700,123623700,104654200
3,2024-01-03,182.18777465820312,456.23455810546875,238.4499969482422,183.7995356475199,458.5702737454352,245.67999267578125,181.37694529807916,455.631168116003,236.32000732421875,182.15811164141854,457.83061907435547,244.97999572753906,58414500,103585900,121082600
4,2024-01-04,179.87393188476562,454.7650146484375,237.92999267578125,181.04071720671112,458.34644746704663,242.6999969482422,178.85546161628733,454.54116395968543,237.72999572753906,180.11123597031312,455.75768568069975,239.25,71983600,84232200,102629300

In [ ]:
market_data.drop(1).reset_index(drop=True)

,Price,Close,Close.1,Close.2,High,High.1,High.2,Low,Low.1,Low.2,Open,Open.1,Open.2,Volume,Volume.1,Volume.2
0,Ticker,AAPL,SPY,TSLA,AAPL,SPY,TSLA,AAPL,SPY,TSLA,AAPL,SPY,TSLA,AAPL,SPY,TSLA
1,2024-01-02,183.56219482421875,459.9911804199219,248.4199981689453,186.33085840634024,460.9838811377681,251.25,181.83178197139316,457.8890273530107,244.41000366210938,185.05528848269014,459.51431341639926,250.0800018310547,82488700,123623700,104654200
2,2024-01-03,182.18777465820312,456.23455810546875,238.4499969482422,183.7995356475199,458.5702737454352,245.67999267578125,181.37694529807916,455.631168116003,236.32000732421875,182.15811164141854,457.83061907435547,244.97999572753906,58414500,103585900,121082600
3,2024-01-04,179.87393188476562,454.7650146484375,237.92999267578125,181.04071720671112,458.34644746704663,242.6999969482422,178.85546161628733,454.54116395968543,237.72999572753906,180.11123597031312,455.75768568069975,239.25,71983600,84232200,102629300
4,2024-01-05,179.15213012695312,455.387939453125,237.49000549316406,180.7144477397177,457.8404368275673,240.1199951171875,178.15344001418788,453.9378252017517,234.89999389648438,179.953076851374,454.9694333616534,236.86000061035156,62379700,86118900,92488900
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
247,2024-12-23,253.6494140625,586.1866455078125,430.6000061035156,254.02699130961165,586.7879087972127,434.510009765625,251.84096111600803,579.2571372355378,415.4100036621094,253.15258832932108,582.4409930028329,431.0,40858800,57635800,72698100
248,2024-12-24,256.5608215332031,592.7021484375,462.2799987792969,256.5707374276886,592.7416149913781,462.7799987792969,253.66927695641888,586.9554933157183,435.1400146484375,253.868019379837,587.5370835235541,435.8999938964844,23234700,33160100,59551800
249,2024-12-26,257.3756103515625,592.7415771484375,454.1300048828125,258.44877099351584,593.8652307760627,465.3299865722656,255.99445048269988,589.5281816588665,451.0199890136719,256.5508929178466,590.9278604962976,465.1600036621094,27237100,41219100,76366400
250,2024-12-27,253.96737670898438,586.5020751953125,431.6600036621094,257.05764856283577,589.2324867459512,450.0,251.45343969164696,582.3128451341881,426.5,256.19314630806485,588.9958679237085,449.5199890136719,42355300,64969300,82666800
251,2024-12-30,250.59889221191406,579.80908203125,417.4100036621094,251.8906421270002,583.2787692142718,427.0,249.15810064436016,576.0535631828352,415.75,250.6287005424076,579.4838439796579,419.3999938964844,35557500,56578800,64941000

In [7]:
market_data.to_json("data/market_data.json")

In [8]:
market_data_json = pd.read_json("data/market_data.json")
market_data_json.head()

,Price,Close,Close.1,Close.2,High,High.1,High.2,Low,Low.1,Low.2,Open,Open.1,Open.2,Volume,Volume.1,Volume.2
0,Ticker,AAPL,SPY,TSLA,AAPL,SPY,TSLA,AAPL,SPY,TSLA,AAPL,SPY,TSLA,AAPL,SPY,TSLA
1,Date,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
2,2024-01-02,183.56219482421875,459.9911804199219,248.4199981689453,186.33085840634024,460.9838811377681,251.25,181.83178197139316,457.8890273530107,244.41000366210938,185.05528848269014,459.51431341639926,250.0800018310547,82488700,123623700,104654200
3,2024-01-03,182.18777465820312,456.23455810546875,238.4499969482422,183.7995356475199,458.5702737454352,245.67999267578125,181.37694529807916,455.631168116003,236.32000732421875,182.15811164141854,457.83061907435547,244.97999572753906,58414500,103585900,121082600
4,2024-01-04,179.87393188476562,454.7650146484375,237.92999267578125,181.04071720671112,458.34644746704663,242.6999969482422,178.85546161628733,454.54116395968543,237.72999572753906,180.11123597031312,455.75768568069975,239.25,71983600,84232200,102629300

In [13]:
import yfinance as yf 
aapl = yf.download("AAPL", start="2024-01-01", end="2024-12-31")

aapl.to_csv("data/aapl.csv")
pd.read_csv("data/aapl.csv").head()

[*********************100%***********************]  1 of 1 completed

,Price,Close,High,Low,Open,Volume
0,Ticker,AAPL,AAPL,AAPL,AAPL,AAPL
1,Date,NaN,NaN,NaN,NaN,NaN
2,2024-01-02,183.5622100830078,186.3308738952772,181.83179708633995,185.05530386559408,82488700
3,2024-01-03,182.187744140625,183.79950485996184,181.37691491631995,182.15808112880916,58414500
4,2024-01-04,179.87393188476562,181.04071720671112,178.85546161628733,180.11123597031312,71983600