In [1]:
import pandas as pd
titanic = pd.read_csv("data/titanic.csv")

In [2]:
titanic["Age"].mean()

np.float64(29.69911764705882)

In [3]:
titanic[["Age", "Fare"]].median()

Age     28.0000
Fare    14.4542
dtype: float64

In [5]:
titanic.agg(
    {
        "Age": ["min", "max", "median", "skew"],
        "Fare": ["min", "max", "median", "mean"],
    }
)

              Age        Fare
min      0.420000    0.000000
max     80.000000  512.329200
median  28.000000   14.454200
skew     0.389108         NaN
mean          NaN   32.204208

In [6]:
titanic[["Sex", "Age"]].groupby("Sex").mean()

              Age
Sex
female  27.915709
male    30.726645

In [8]:
titanic_mean = titanic.groupby("Sex").mean(numeric_only=True)
titanic_mean

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
Sex,,,,,,,
female,431.028662,0.742038,2.159236,27.915709,0.694268,0.649682,44.479818
male,454.147314,0.188908,2.389948,30.726645,0.429809,0.235702,25.523893

In [13]:
titanic_mean = titanic_mean.drop(columns=["Pclass"])
titanic_mean

        PassengerId  Survived        Age     SibSp     Parch       Fare
Sex
female   431.028662  0.742038  27.915709  0.694268  0.649682  44.479818
male     454.147314  0.188908  30.726645  0.429809  0.235702  25.523893

In [16]:
titanic.groupby("Sex")[["Age", "Survived", "Fare"]].mean()

              Age  Survived       Fare
Sex
female  27.915709  0.742038  44.479818
male    30.726645  0.188908  25.523893

In [17]:
titanic.groupby(["Sex", "Pclass"])["Fare"].mean()

Sex     Pclass
female  1         106.125798
        2          21.970121
        3          16.118810
male    1          67.226127
        2          19.741782
        3          12.661633
Name: Fare, dtype: float64

In [18]:
titanic["Pclass"].value_counts()

Pclass
3    491
1    216
2    184
Name: count, dtype: int64

In [19]:
titanic.groupby("Pclass")["Pclass"].count()

Pclass
1    216
2    184
3    491
Name: Pclass, dtype: int64